"""Tally a blind-trial grades file into FRESH_TRIAL_REPORT.md, split by strategy.

Inputs:
  * grades.json  — ``{item_id: {marks: {b0,p0,e0,...: bool}, verdict: str}}`` written by
    the inspect viewer's blind grading panel.
  * unblind.json — ``{item_id: {episode_id, strategy, bands, denom: {b,p,e}}}`` written by
    ``build_inspect_data.py from-annotations --blind`` (the identity + denominators map).

Two grading protocols:
  * ``mark-failures-only`` (default) — the grader marks only the failures and leaves the
    rest blank; an unmarked question counts as a **pass** over the known denominator
    (number of boundaries / phases / evidence slots in the graded items). This matches how
    a human actually grades.
  * ``mark-all`` — every question was answered yes/no; rate = mean of the marks entered.

Metrics per strategy: boundary acceptance (±5f), phase accuracy, evidence factual-accuracy
(OURS), failure-band rate (objective, from the bands), verdict distribution.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def tally(grades: dict[str, Any], unblind: dict[str, Any], protocol: str = "mark-failures-only") -> dict[str, Any]:
    by: dict[str, dict[str, Any]] = {}
    for item_id, g in grades.items():
        meta = unblind.get(item_id)
        if not meta:
            continue
        strat = meta.get("strategy", "?")
        denom = meta.get("denom", {})
        marks = g.get("marks", {})
        s = by.setdefault(strat, {"n_items": 0, "bands": [], "verdict": [],
                                  "b_d": 0, "b_f": 0, "b_marks": [], "p_d": 0, "p_f": 0, "p_marks": [],
                                  "e_d": 0, "e_f": 0, "e_marks": []})
        s["n_items"] += 1
        s["bands"].append(bool(meta.get("bands")))
        if g.get("verdict"):
            s["verdict"].append(g["verdict"])
        for kind, dkey in (("b", "b"), ("p", "p"), ("e", "e")):
            present = [v for k, v in marks.items() if k.startswith(kind)]
            s[f"{kind}_marks"].extend(present)
            s[f"{kind}_d"] += int(denom.get(dkey, 0))
            s[f"{kind}_f"] += sum(1 for v in present if v is False)

    out = {}
    for strat, s in by.items():
        rates = {}
        for kind in ("b", "p", "e"):
            if protocol == "mark-all":
                m = s[f"{kind}_marks"]
                rates[kind] = (sum(1 for v in m if v) / len(m)) if m else None
                rates[f"{kind}_n"] = len(m)
            else:  # mark-failures-only: unmarked = pass over the denominator
                d = s[f"{kind}_d"]
                rates[kind] = (1 - s[f"{kind}_f"] / d) if d else None
                rates[f"{kind}_n"] = d
        n = s["n_items"]
        fb = sum(1 for x in s["bands"] if x)
        out[strat] = {
            "n_items": n,
            "boundary_acceptance": rates["b"], "n_boundaries": rates["b_n"],
            "phase_accuracy": rates["p"], "n_phases": rates["p_n"],
            "evidence_factual_accuracy": rates["e"], "n_evidence": rates["e_n"],
            "failure_band_rate": (fb / n if n else None), "n_failure_band": fb,
            "verdicts": {v: s["verdict"].count(v) for v in ("usable", "touchup", "garbage")},
        }
    return out


def write_trial_report(grades_path: str | Path, unblind_path: str | Path, out_path: str | Path,
                       protocol: str = "mark-failures-only") -> str:
    grades = json.loads(Path(grades_path).read_text(encoding="utf-8"))
    unblind = json.loads(Path(unblind_path).read_text(encoding="utf-8"))
    t = tally(grades, unblind, protocol=protocol)
    dataset = unblind.get("__dataset__", "(fresh dataset)")

    def pct(x):
        return "n/a" if x is None else f"{x:.2f}"

    proto_line = (
        "Grading protocol: **mark-failures-only** — the grader marked only the failures; "
        "every unmarked boundary/phase/evidence counts as a pass over the known denominator."
        if protocol == "mark-failures-only"
        else "Grading protocol: **mark-all** — rate = mean of the yes/no marks entered."
    )
    lines = [
        "<!-- generated by robolabel trial-report -->",
        f"Dataset: **{dataset}**. {proto_line}",
        f"Items graded: **{sum(v['n_items'] for v in t.values())}**.",
        "",
        "| strategy | items | boundary acceptance (±5f) | phase accuracy | **evidence factual-accuracy** | failure-band rate | usable / touch-up / garbage |",
        "|---|---|---|---|---|---|---|",
    ]
    for strat in sorted(t):
        v = t[strat]
        ver = v["verdicts"]
        lines.append(
            f"| {strat} | {v['n_items']} | {pct(v['boundary_acceptance'])} (n={v['n_boundaries']}) "
            f"| {pct(v['phase_accuracy'])} (n={v['n_phases']}) "
            f"| **{pct(v['evidence_factual_accuracy'])}** (n={v['n_evidence']}) "
            f"| {pct(v['failure_band_rate'])} "
            f"| {ver['usable']} / {ver['touchup']} / {ver['garbage']} |"
        )
    Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(out_path)
